name = "modpack_forge"
author = "kuromau521"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c95594ab28786510d726f1b4f3412eb7a147644f79867f6894a8aeacbe1f41a5"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
