name = "modpack_forge"
author = "kuromau521"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33b462fdbcb9d9e914e542c684df659032a576de4455e937eb393b29d50e6435"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
