name = "modpack_forge"
author = "kuromau521"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "646bf379d92a9625d52bd01f7810d57da446673b7b91b9b371fd84296ae00d21"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
